#!/usr/bin/env python3
"""
Test script for nuclear feature clustering column name compatibility.

Author: Christos Botos
Email: hcty02@gmail.com
Date: 2025-07-31

Description:
    This test verifies that the clustering script correctly handles the lowercase
    column names generated by the feature extraction pipeline. It ensures that
    the column name mismatch issue has been resolved and that clustering works
    with the actual CSV format produced by the pipeline.

Dependencies:
    • Python >= 3.10.
    • pandas, numpy for data handling.
    • pathlib for file operations.

Usage:
    python tests/test_clustering_column_names.py

Inputs:
    • Engineered features CSV file with lowercase column names.
    • Test validates column name compatibility.

Outputs:
    • Test results showing successful column name handling.
    • Validation of clustering script compatibility.

Key Features:
    • Column name validation for clustering compatibility.
    • CSV format verification.
    • Error handling for missing columns.

Notes:
    • This test ensures the clustering script works with actual pipeline outputs.
    • Validates the fix for uppercase/lowercase column name mismatch.
    • Critical for maintaining pipeline compatibility.
"""

import traceback
import sys
import pandas as pd
import numpy as np
from pathlib import Path
import tempfile
import logging

# Configure logging for test output.
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)


def create_test_features_csv(output_path: Path) -> None:
    """
    Create a test CSV file with the correct lowercase column names.
    
    Args:
        output_path: Path where to save the test CSV file.
        
    This function generates a small test dataset with the same column structure
    as the actual feature extraction pipeline output, using lowercase names.
    """
    logger.info("Creating test features CSV with lowercase column names.")
    
    # Generate synthetic test data with correct column names.
    n_nuclei = 100
    np.random.seed(42)
    
    test_data = {
        'label': np.arange(1, n_nuclei + 1),
        'centroid_x': np.random.uniform(10, 500, n_nuclei),
        'centroid_y': np.random.uniform(10, 500, n_nuclei),
        'circularity': np.random.uniform(0.5, 1.0, n_nuclei),
        'eccentricity': np.random.uniform(0.1, 0.9, n_nuclei),
        'solidity': np.random.uniform(0.8, 1.0, n_nuclei),
        'aspect_ratio': np.random.uniform(1.0, 3.0, n_nuclei),
        'area': np.random.uniform(50, 300, n_nuclei),
        'perimeter': np.random.uniform(20, 80, n_nuclei),
        'major_axis_length': np.random.uniform(8, 25, n_nuclei),
        'minor_axis_length': np.random.uniform(6, 20, n_nuclei)
    }
    
    df = pd.DataFrame(test_data)
    df.to_csv(output_path, index=False)
    
    logger.info(f"✓ Created test CSV with {len(df)} nuclei and {len(df.columns)} columns.")


def test_column_name_compatibility() -> bool:
    """
    Test that the clustering script can handle lowercase column names.
    
    Returns:
        True if test passes, False otherwise.
        
    This function tests the core functionality that was fixed: ensuring the
    clustering script correctly reads CSV files with lowercase column names.
    """
    logger.info("Testing column name compatibility for clustering script.")
    
    try:
        # Import the clustering functions.
        sys.path.append(str(Path(__file__).parent.parent / 'code' / 'engineered_feature_extraction'))
        from cluster_engineered_features import load_nuclear_features, prepare_feature_matrix
        
        # Create temporary test file.
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False) as tmp_file:
            tmp_path = Path(tmp_file.name)
        
        try:
            # Create test data.
            create_test_features_csv(tmp_path)
            
            # Test loading features with lowercase column names.
            logger.info("Testing load_nuclear_features function.")
            df = load_nuclear_features(tmp_path)
            
            # Verify required columns are present.
            required_cols = ['label', 'centroid_x', 'centroid_y']
            missing_cols = [col for col in required_cols if col not in df.columns]
            
            if missing_cols:
                logger.error(f"✗ Missing required columns: {missing_cols}")
                return False
            
            logger.info("✓ Successfully loaded features with lowercase column names.")
            
            # Test feature matrix preparation.
            logger.info("Testing prepare_feature_matrix function.")
            features, feature_names, nuclear_labels = prepare_feature_matrix(df)
            
            # Verify outputs.
            if features.shape[0] != len(df):
                logger.error(f"✗ Feature matrix has wrong number of rows: {features.shape[0]} vs {len(df)}")
                return False
            
            if len(nuclear_labels) != len(df):
                logger.error(f"✗ Nuclear labels have wrong length: {len(nuclear_labels)} vs {len(df)}")
                return False
            
            # Verify nuclear labels match the 'label' column.
            expected_labels = df['label'].values
            if not np.array_equal(nuclear_labels, expected_labels):
                logger.error("✗ Nuclear labels don't match expected values.")
                return False
            
            logger.info("✓ Successfully prepared feature matrix with correct labels.")
            logger.info(f"✓ Feature matrix shape: {features.shape}")
            logger.info(f"✓ Number of feature columns: {len(feature_names)}")
            
            return True
            
        finally:
            # Clean up temporary file.
            if tmp_path.exists():
                tmp_path.unlink()
                
    except Exception as e:
        logger.error(f"✗ Test failed with exception: {str(e)}")
        logger.error(traceback.format_exc())
        return False


def test_csv_format_validation() -> bool:
    """
    Test CSV format validation with various column name scenarios.
    
    Returns:
        True if all validation tests pass, False otherwise.
        
    This function tests edge cases and ensures robust error handling for
    different CSV formats and column name variations.
    """
    logger.info("Testing CSV format validation.")
    
    try:
        sys.path.append(str(Path(__file__).parent.parent / 'code' / 'engineered_feature_extraction'))
        from cluster_engineered_features import load_nuclear_features
        
        # Test 1: Missing required column.
        logger.info("Test 1: CSV missing 'label' column.")
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False) as tmp_file:
            tmp_path = Path(tmp_file.name)
        
        try:
            # Create CSV without 'label' column.
            test_data = pd.DataFrame({
                'centroid_x': [100, 200],
                'centroid_y': [150, 250],
                'area': [120, 180]
            })
            test_data.to_csv(tmp_path, index=False)
            
            # This should raise an error.
            try:
                load_nuclear_features(tmp_path)
                logger.error("✗ Expected error for missing 'label' column, but none occurred.")
                return False
            except ValueError as e:
                if "Missing required columns: ['label']" in str(e):
                    logger.info("✓ Correctly detected missing 'label' column.")
                else:
                    logger.error(f"✗ Unexpected error message: {str(e)}")
                    return False
                    
        finally:
            if tmp_path.exists():
                tmp_path.unlink()
        
        # Test 2: Correct lowercase columns.
        logger.info("Test 2: CSV with correct lowercase columns.")
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False) as tmp_file:
            tmp_path = Path(tmp_file.name)
        
        try:
            test_data = pd.DataFrame({
                'label': [1, 2, 3],
                'centroid_x': [100, 200, 300],
                'centroid_y': [150, 250, 350],
                'area': [120, 180, 200],
                'circularity': [0.8, 0.9, 0.7]
            })
            test_data.to_csv(tmp_path, index=False)
            
            df = load_nuclear_features(tmp_path)
            if len(df) != 3:
                logger.error(f"✗ Expected 3 rows, got {len(df)}")
                return False
            
            logger.info("✓ Successfully loaded CSV with correct lowercase columns.")
            
        finally:
            if tmp_path.exists():
                tmp_path.unlink()
        
        return True
        
    except Exception as e:
        logger.error(f"✗ CSV format validation failed: {str(e)}")
        logger.error(traceback.format_exc())
        return False


def main():
    """
    Run all clustering column name compatibility tests.
    
    This function coordinates all test cases and provides a comprehensive
    validation of the column name fix for the clustering functionality.
    """
    logger.info("🧬 CLUSTERING COLUMN NAME COMPATIBILITY TESTS 🧬")
    logger.info("=" * 60)
    
    tests = [
        ("Column Name Compatibility", test_column_name_compatibility),
        ("CSV Format Validation", test_csv_format_validation)
    ]
    
    passed = 0
    total = len(tests)
    
    for test_name, test_func in tests:
        logger.info(f"\nRunning: {test_name}")
        logger.info("-" * 40)
        
        if test_func():
            logger.info(f"✓ {test_name} PASSED")
            passed += 1
        else:
            logger.error(f"✗ {test_name} FAILED")
    
    logger.info("\n" + "=" * 60)
    logger.info(f"TEST SUMMARY: {passed}/{total} tests passed")
    
    if passed == total:
        logger.info("🎉 All clustering compatibility tests PASSED!")
        return 0
    else:
        logger.error("❌ Some tests FAILED. Please check the clustering implementation.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
